export enum DBErrorType {
    NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
    TABLE_EXISTS = 'TABLE_EXISTS',
    TABLE_NOT_EXISTS = 'TABLE_NOT_EXISTS',
    COLUMN_NOT_EXISTS = 'COLUMN_NOT_EXISTS',
    COLUMN_EXISTS = 'COLUMN_EXISTS',
    ROW_NOT_EXISTS = 'ROW_NOT_EXISTS',
    PK_EXISTS = 'PRIMARY_KEY_EXISTS',
    FK_EXISTS = 'FOREIGN_KEY_EXISTS',
    INSERT_ROW_SIZE = 'INSERT_ROW_SIZE',
    INSERT_MISSING_PK = 'INSERT_MISSING_PK',
    KEY_VIOLATION = 'KEY_VIOLATION',
    DROP_TABLE_ERROR = 'DROP_TABLE_ERROR',
}


export class DBError extends Error {
    constructor(type: DBErrorType, msg: string = '') {
        super(`${type} - ${msg}`)
    }
}